### ISSUE TITLE
Como receber atualização do manual do PowerBI?

### ISSUE THREAD

**Issue by evandroinada** [MicrosoftDocs/powerbi-docs.pt-br#10]
O manual é muito bom, mas como fazer para receber as atualizações do manual do PowerBI?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [Gateway de dados local - Power BI](https://docs.microsoft.com/pt-br/power-bi/service-gateway-onprem)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by CeciAc** [comment]
Olá, @evandroinada 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
