### ISSUE TITLE
Favor complementar o item Aplicar a Previsão

### ISSUE THREAD

**Issue by IsaiasGarcez** [MicrosoftDocs/powerbi-docs.pt-br#11]
Para o correto funcionamento desta análise preditiva no Power BI Desktop é necessário ainda atender aos seguintes requisitos:
- Visual de linha com apenas uma variável
- Eixo X com coluna de data em formato datetime
- Eixo X em configuração de exibição como "Contínua"

Somente desta forma o recurso de previsão é habilitado. Seria interessante ainda alguma explicação sobre o método estatístico aplicado no cálculo.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: fbbf6763-4952-5335-cefb-ae4e85fd9028
* Version Independent ID: cb734eb1-fb6d-b7aa-735a-17b5ba8ca7fd
* Content: [Usando o painel Análise no Power BI Desktop - Power BI](https://docs.microsoft.com/pt-br/power-bi/desktop-analytics-pane#apply-forecasting)
* Content Source: [powerbi-docs/desktop-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/desktop-analytics-pane.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
Olá, @IsaiasGarcez 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
