### ISSUE TITLE
Segmentação de Dados

### ISSUE THREAD

**Issue by ljunior19** [MicrosoftDocs/powerbi-docs.pt-br#12]
[Insira comentários aqui]

Keeping data segmentation selected when switching between panels you have created. So not missing the selection when switching panels?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2f177d47-9600-eab6-a282-09d40d5c2dff
* Version Independent ID: 792909b9-e2fa-8a31-1da9-2223307e799d
* Content: [Tutorial – Segmentação de Dados no Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/visuals/power-bi-visualization-slicers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-slicers.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/visuals/power-bi-visualization-slicers.md)
* Service: **powerbi**
* GitHub Login: @v-thepet
* Microsoft Alias: **mihart**

**Comment by CeciAc** [comment]
Hello, @ljunior19 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ljunior19 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" ( "Comentários sobre o produto") at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
