### ISSUE TITLE
Cartão

### ISSUE THREAD

**Issue by DedersSP** [MicrosoftDocs/powerbi-docs.pt-br#14]
Não consigo alinhar o valor a esquerda e direita? Fica somente centralizado?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: d7b39f54-b688-a2e0-2097-76abe2086b7c
* Version Independent ID: 6376d063-b0b2-21f2-4fb8-506a016caf7d
* Content: [Visualizações de cartão (também conhecido como blocos de números grandes) - Power BI](https://docs.microsoft.com/pt-br/power-bi/visuals/power-bi-visualization-card)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-card.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/visuals/power-bi-visualization-card.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by CeciAc** [comment]
Olá, @DedersSP 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
