### ISSUE TITLE
A informação não procede a respeito do Firefox

### ISSUE THREAD

**Issue by kah600** [MicrosoftDocs/powerbi-docs.pt-br#15]
Meu navegador Firefox está atualizado com a última versão (66.0.3 - Firefox Release de April 10, 2019) e o PowerBI nem sequer abre. Ele processa a requisição e fica totalmente branco, sem exibir qualquer informação. Com o Chrome Versão 73.0.3683.103 (Versão oficial) 64 bits abre normalmente o mesmo dashboard. Sugiro a mudança do artigo para citar exatamente qual versão era compatível com o PowerBI, porque a mais atualizada, de fato, não é.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 753770c6-5424-85a6-1bd7-963e2c1c7e64
* Version Independent ID: 09a4403f-9fbd-535a-4b45-83e89f380ba0
* Content: [Navegadores com suporte para o Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/consumer/end-user-browsers#feedback)
* Content Source: [powerbi-docs/consumer/end-user-browsers.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/consumer/end-user-browsers.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #982](https://github.com/MicrosoftDocs/powerbi-docs/issues/982) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Olá, @kah600 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/powerbi-docs/issues/982

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
