### ISSUE TITLE
Dados do site não estão mais atualizados

### ISSUE THREAD

**Issue by thiagollrc** [MicrosoftDocs/powerbi-docs.pt-br#18]
Prezados, estou estudando PowerBI mas a tabela do site "http://www.bankrate.com/finance/retirement/best-places-retire-how-state-ranks.aspx" não traz mais todas as colunas como esta página indica. Sugiro uma atualização.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Introdução ao Power BI Desktop - Power BI](https://docs.microsoft.com/pt-br/power-bi/desktop-getting-started#feedback)
* Content Source: [powerbi-docs/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Olá, @thiagollrc 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/powerbi-docs/issues/1136

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
