### ISSUE TITLE
TXT/CSV File

### ISSUE THREAD

**Issue by MoizesMedes** [MicrosoftDocs/powerbi-docs.pt-br#19]
I'm trying to take a csv file in a OneDrive folder. How can I do that?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 92a1e2f2-6f7a-06ab-77a5-efff8aedabe3
* Version Independent ID: 67d3cd28-51ec-07d9-ed36-840097415f56
* Content: [Usar os links do OneDrive for Business no Power BI Desktop - Power BI](https://docs.microsoft.com/pt-br/power-bi/desktop-use-onedrive-business-links#feedback)
* Content Source: [powerbi-docs/desktop-use-onedrive-business-links.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/desktop-use-onedrive-business-links.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by lichasu** [comment]
Hello, @MoizesMedes,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
