### ISSUE TITLE
Compartilhar um relatório para pessoas fora da organização

### ISSUE THREAD

**Issue by marcelosalata** [MicrosoftDocs/powerbi-docs.pt-br#2]
A documentação não informou o que e como parametrizar o PowerBi para permitir o compartilhamento com pessoas fora da organização. Somente informa o que estas pessoas podem ou não podem ver.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Compartilhe os painéis e os relatórios do Power BI com colegas e outras pessoas - Power BI](https://docs.microsoft.com/pt-br/power-bi/service-share-dashboards#share-a-dashboard-or-report-with-people-outside-your-organization)
* Content Source: [powerbi-docs/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/service-share-dashboards.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by LisandroSu** [comment]
Olá, @marcelosalata , 

Agradecemos seus comentários. 

Vamos analisar seus comentários e daremos um retorno para você em breve. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #164](https://github.com/MicrosoftDocs/powerbi-docs/issues/164) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Olá, @marcelosalata , 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 

Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/powerbi-docs/issues/164. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
