### ISSUE TITLE
Não consigo conectar os dados.

### ISSUE THREAD

**Issue by IsaqueM** [MicrosoftDocs/powerbi-docs.pt-br#22]
Olá. Eu fiz todo o procedimento, mas, no passo 10 de "Como se Conectar", não acho nenhum botã ou referencia de "Conectar" como está no segmento 10: "Clique em Conectar para iniciar o processo de importação."
Gostaria de saber como faço para me conectar, assim, conseguindo importar meus dados do Zendesk para o Power BI.

Desde já grato!

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2231f5c7-c73c-0b80-d6b9-5adf207a6b62
* Version Independent ID: 91e7c633-83d4-0714-e92f-e3f169549bd5
* Content: [Conectar-se ao Zendesk com o Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/service-connect-to-zendesk#feedback)
* Content Source: [powerbi-docs/service-connect-to-zendesk.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/service-connect-to-zendesk.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @IsaqueM
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @IsaqueM 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
