### ISSUE TITLE
Janelas não abrem no tamanho normal

### ISSUE THREAD

**Issue by LUCKLESPP** [MicrosoftDocs/powerbi-docs.pt-br#24]
Ao acessar o menu "Arquivo &gt; Opções e configurações" as janelas "Opções" ou "configurações" não abrem com o tamanho normal! Qual a solução? 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 57120f28-dce7-01db-855c-33e40721776f
* Version Independent ID: e8c49eaf-3bed-ed73-0512-c7adda73bcb3
* Content: [Solucionar problemas de entrada no Power BI Desktop - Power BI](https://docs.microsoft.com/pt-br/power-bi/desktop-troubleshooting-sign-in#feedback)
* Content Source: [powerbi-docs/desktop-troubleshooting-sign-in.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/desktop-troubleshooting-sign-in.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @LUCKLESPP
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @LUCKLESPP

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
