### ISSUE TITLE
RLS - Não funciona no Conjunto de Dados

### ISSUE THREAD

**Issue by lfalexandre** [MicrosoftDocs/powerbi-docs.pt-br#27]
Fiz o procedimento descrito para a segurança RLS, o qual funciona perfeitamente a nível de relatório, entretanto se o usuário se conecta via Conjunto de Dados pelo Power BI Desktop, o filtro RLS não funciona e o usuário tem acesso total ao Conjunto mesmo se ele estiver classificado como Visualizador.

Obrigado

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [RLS (segurança em nível de linha) com o Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by srvbpigh** [comment]
Hello, @lfalexandre
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1467](https://github.com/MicrosoftDocs/powerbi-docs/issues/1467) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Olá, @lfalexandre 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/powerbi-docs/issues/1467

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
