### ISSUE TITLE
"Lista pendente" vira "lista" na publicação

### ISSUE THREAD

**Issue by viniciuscbarqueiro** [MicrosoftDocs/powerbi-docs.pt-br#29]
Eu crio uma segmentação em **lista suspensa**:
![image](https://user-images.githubusercontent.com/57196999/67896452-255ced00-fb3b-11e9-83bb-8548ecca741e.png)

Quando publico, ela se transforma em apenas **lista**:
![image](https://user-images.githubusercontent.com/57196999/67896396-09594b80-fb3b-11e9-9acd-37216b3cc5aa.png)

Alguém pode me ajudar, por favor? Preciso que sigam como lista suspensa.

**Comment by srvbpigh** [comment]
Hello, @viniciuscbarqueiro
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @viniciuscbarqueiro 

Apreciamos muito a sua contribuição. Ainda assim, esses comentários se referem a produtos. Registre sua sugestão usando o botão "Fornecer comentários sobre produtos" na parte inferior da página do DOCS.

Se você tiver qualquer comentário relacionado a documentação, sinta-se livre para registrá-lo por este canal.

Verdadeiramente apreciamos sua contribuição para os nossos artigos.

Equipe internacional do Microsoft DOCS
