### ISSUE TITLE
Nao respondeu a pergunta

### ISSUE THREAD

**Issue by robertopsilva** [MicrosoftDocs/powerbi-docs.pt-br#3]
Veja, neste tutorial de linguagens, mostra como modificar de diversas formas, mas para qual versão este tutorial foi projetado? na minha versão de power b.i não existe a opção regional settings dentro das opções Global. Apenas regional settings dentro de current file !

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: d01f4ea6-33ff-97ca-4a4e-8a1beb88f12f
* Version Independent ID: e5224487-369d-23be-98cb-ebab58c75ac4
* Content: [Idiomas com suporte e países/regiões para o Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/supported-languages-countries-regions)
* Content Source: [powerbi-docs/supported-languages-countries-regions.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/supported-languages-countries-regions.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by LisandroSu** [comment]
Olá, @robertopsilva 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Enviar Comentários do Produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
