### ISSUE TITLE
Consultar várias páginas na web.

### ISSUE THREAD

**Issue by PauloDominonni** [MicrosoftDocs/powerbi-docs.pt-br#30]
Por favor poderia me ajudar em como fazer uma consulta em uma página da web que possui as tabelas em várias páginas. 
Muito obrigado

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: c2e2c100-ccb2-a69b-cd7c-f564441c573d
* Version Independent ID: f37af593-9e1f-9bb4-e5d8-b5500505f6a5
* Content: [Tutorial: Importar e analisar dados de uma página da Web - Power BI](https://docs.microsoft.com/pt-br/power-bi/desktop-tutorial-importing-and-analyzing-data-from-a-web-page?source=docs#feedback)
* Content Source: [powerbi-docs/desktop-tutorial-importing-and-analyzing-data-from-a-web-page.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/desktop-tutorial-importing-and-analyzing-data-from-a-web-page.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @PauloDominonni
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @PauloDominonni

Apreciamos muito a sua contribuição. Ainda assim, esses comentários se referem a produtos. Registre sua sugestão usando o botão "Fornecer comentários sobre produtos" na parte inferior da página do DOCS.

Se você tiver qualquer comentário relacionado a documentação, sinta-se livre para registrá-lo por este canal.

Verdadeiramente apreciamos sua contribuição para os nossos artigos.

Equipe internacional do Microsoft DOCS
