### ISSUE TITLE
Efficiency

### ISSUE THREAD

**Issue by thiago-mpm** [MicrosoftDocs/powerbi-docs.pt-br#31]
Hello! 

I have been working with two main tables, budget and expenses. He gave me the idea of merging them both and create the tables and grafics based on this single table. Is there any reason for me not to do it? It would end the need for relationships, for exemple.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 470ca67d-ed62-fbe0-85b2-6b1604f9f946
* Version Independent ID: e8c82d66-ad63-3efa-11b2-060b9b16d4ad
* Content: [Entenda o esquema em estrela e a importância para o Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/guidance/star-schema?source=docs#feedback)
* Content Source: [powerbi-docs/guidance/star-schema.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/guidance/star-schema.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by srvbpigh** [comment]
Hello, @thiago-mpm
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by thiago-mpm** [comment]
In another way, why shouldn't a table be a dimention-type and a fact-type table at the same time?

**Comment by peter-myers** [comment]
Hi Thiago - great question! When the dimensionality and the grain of your budgets and expenses are the same, you can consider integrating them into a single table. This would involve adding a column to allow you to filter by scenario (in this case, actual and budget). However, in the real-world commonly budget (and forecast) scenarios are stored more simply, often with lower dimensionality and/or higher grain (for example, month, quarter or year level). So, it's not always possible. I hope this helps! #please-close

**Comment by thiago-mpm** [comment]
So, basically, if I can manage to have them with the same dimensionality and grain, there's no bad side in using them in a single table? That is super couterintuitive, but I believe.

**Comment by CeciAc** [comment]
Hello, @thiago-mpm

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
