### ISSUE TITLE
Requisitos Mínimos do Desktop

### ISSUE THREAD

**Issue by asfalcao** [MicrosoftDocs/powerbi-docs.pt-br#32]
Tenho um notebook com 8 GB de RAM, SSD de 240 GB 450 MB/s de escrita e leitura, processador Intel Core i5 de quarta geração e placa aceleradora gráfica nVidia com memória dedicada de 2 GB, Windows Pro 64 bits (versão 1909) e Power BI de 64 bits instalados.
Utilizar o Power BI  nessa plataforma é uma aventura porque ao se utilizar funções avançadas o notebook deixa a desejar.
E digo que edito filmes full HD nele sem problemas. 
Creio que os requisitos mínimos são insuficientes.
Num outro equipamento com Core i7 de sexta geração, e outros recursos similares ao equipamento Core i5, aí sim, o Power BI funciona.   

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 322970ff-d62a-adeb-c8b3-d1141d3a272f
* Version Independent ID: 94d82157-a824-73c8-2add-462ee6b033b1
* Content: [Obter o Power BI Desktop - Power BI](https://docs.microsoft.com/pt-br/power-bi/desktop-get-the-desktop#feedback)
* Content Source: [powerbi-docs/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @asfalcao
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @asfalcao 

Apreciamos muito a sua contribuição. Ainda assim, esses comentários se referem a produtos. Registre sua sugestão usando o botão "Fornecer comentários sobre produtos" na parte inferior da página do DOCS.

Se você tiver qualquer comentário relacionado a documentação, sinta-se livre para registrá-lo por este canal.

Verdadeiramente apreciamos sua contribuição para os nossos artigos.

Equipe internacional do Microsoft DOCS
