### ISSUE TITLE
Muito Bom!

### ISSUE THREAD

**Issue by jonas91j** [MicrosoftDocs/powerbi-docs.pt-br#33]
Como sou iniciante em Power Bi , as fórmulas DAX estão parecendo muito confusas e complexas pra mim.  Fazer coisas que considero simples na linguagem SQL está sendo um desafio tremendo em DAX.  Esse artigo tornou um dos cenários que enfrento mais fácil de entender. 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 25ae9c4f-cf07-3579-9ad1-07cec420c734
* Version Independent ID: 7f528784-5e65-1d8e-2f4f-86e3d15567ce
* Content: [DAX: Usar variáveis para melhorar as fórmulas - Power BI](https://docs.microsoft.com/pt-br/power-bi/guidance/dax-variables#feedback)
* Content Source: [powerbi-docs/guidance/dax-variables.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/guidance/dax-variables.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by srvbpigh** [comment]
Hello, @jonas91j
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @jonas91j 

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas. 

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência.

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
