### ISSUE TITLE
conta

### ISSUE THREAD

**Issue by lucas378** [MicrosoftDocs/powerbi-docs.pt-br#34]
Como faço para reabrir uma conta. pois não está mais deste tipo com esse icone para "reopen your account"

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: c12dd3d7-8816-3a42-a21d-2c0600a83b44
* Version Independent ID: 2f443100-7d3c-0766-c0fd-2979cdc41fe4
* Content: [Fechar sua conta do Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/service-admin-closing-your-account#feedback)
* Content Source: [powerbi-docs/service-admin-closing-your-account.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/service-admin-closing-your-account.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by srvbpigh** [comment]
Hello, @lucas378
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1940](https://github.com/MicrosoftDocs/powerbi-docs/issues/1940) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Olá, @lucas378,   

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original.  

Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/powerbi-docs/issues/1940.  

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente,  
Equipe Internacional do Microsoft DOCS
