### ISSUE TITLE
Erro ao tentar obter dados da Web no Power BI

### ISSUE THREAD

**Issue by guerraguilherme** [MicrosoftDocs/powerbi-docs.pt-br#35]
Quando tento obter dados de páginas da web, mesmo aquelas sugeridas em tutoriais fornecidos pela Microsoft, o programa responde com o seguinte erro: 
"Não é possível estabelecer conexão
Encontramos um erro ao tentar conectar.
Detalhes: 'Erro desconhecido ao navegar para a página da Web."
Minha internet está funcionando perfeitamente, já reiniciei o programa e o computador, porém o erro persiste. Quais outras coisas posso fazer para tentar resolver esse problema?
Obrigado!

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 8d1bfb7d-4e9e-27c5-ece0-74511f99136e
* Version Independent ID: 1a9b344d-65ea-518a-03db-3636ea3fb48f
* Content: [Conectar-se a uma página da Web no Power BI Desktop - Power BI](https://docs.microsoft.com/pt-br/power-bi/desktop-connect-to-web#feedback)
* Content Source: [powerbi-docs/desktop-connect-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/desktop-connect-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @guerraguilherme
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @guerraguilherme 

Apreciamos muito a sua contribuição. Ainda assim, esses comentários se referem a produtos. Registre sua sugestão usando o botão "Fornecer comentários sobre produtos" na parte inferior da página do DOCS. 

Se você tiver qualquer comentário relacionado a documentação, sinta-se livre para registrá-lo por este canal. 

Verdadeiramente apreciamos sua contribuição para os nossos artigos.  

Equipe internacional do Microsoft DOCS
