### ISSUE TITLE
Onde esta o link?

### ISSUE THREAD

**Issue by daltonpinheiro** [MicrosoftDocs/powerbi-docs.pt-br#36]
Ok, pbubliquei o documento. 
Onde está o link desta publicação para passar para outras pessoas usar?
É possível usar este recurso com uma conta free, pois eu conseguia e não estou conseguindo mais?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: ef5362a0-2148-3de0-fd60-a3fe5d06fe91
* Version Independent ID: 1967384e-308d-cf6f-ad5f-cde6e5b741b3
* Content: [Publicar por meio do Power BI Desktop - Power BI](https://docs.microsoft.com/pt-br/power-bi/desktop-upload-desktop-files#feedback)
* Content Source: [powerbi-docs/desktop-upload-desktop-files.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/desktop-upload-desktop-files.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @daltonpinheiro
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #2114](https://github.com/MicrosoftDocs/powerbi-docs/issues/2114) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Olá, @daltonpinheiro,   

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original.  

Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/powerbi-docs/issues/2114.  

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente,  
Equipe Internacional do Microsoft DOCS
