### ISSUE TITLE
Falta de consideração para com o cliente, alegam suportar acima de Office 2010 SP1 mas não suporte Office 2013

### ISSUE THREAD

**Issue by henriquesantosneto** [MicrosoftDocs/powerbi-docs.pt-br#37]
[Insira comentários aqui]
Falam que o requisito mínimo é o Office 2010 SP1, o que é uma mentira, pois no office 2013 não funciona e o suporte da Microsoft não está nem ligando para o cliente, não conseguem sequer resolver um problema ridículo de Office. Então que coloquem as edições realmente compatíveis.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analisar no Excel para o Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/collaborate-share/service-analyze-in-excel)
* Content Source: [powerbi-docs/collaborate-share/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/collaborate-share/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @henriquesantosneto
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #2282](https://github.com/MicrosoftDocs/powerbi-docs/issues/2282) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Olá, @henriquesantosneto,   

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original.  

Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/powerbi-docs/issues/2282.  

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente,  
Equipe Internacional do Microsoft DOCS
