### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by lucasvaliente2** [MicrosoftDocs/powerbi-docs.pt-br#4]
Boa tarde,
Estou com esse erro
Não foi possível analisar o resultado da resposta de OData.  Erro: The property 'EnableRequestSignOff' does not exist on type 'SP.List'. Make sure to only use property names that are defined by the type. 
na hora de puxar os dados do sharepoint e não estou encontrando a solução, alguem pode me ajudar?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: d6fe0913-78f9-47f1-ead1-dbecb17127d6
* Version Independent ID: 5828f2fc-25ae-18d8-a9ac-786511478fbe
* Content: [Solucionando problemas de erros de bloco - Power BI](https://docs.microsoft.com/pt-br/power-bi/refresh-troubleshooting-tile-errors)
* Content Source: [powerbi-docs/refresh-troubleshooting-tile-errors.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/refresh-troubleshooting-tile-errors.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
Olá, @lucasvaliente2 ,

Sua contribuição é muito   bem-vinda. Nossa equipe só pode responder a comentários relacionados à   documentação.
 
Registre os comentários do seu   produto usando o botão "Enviar Comentários do   Produto" na parte inferior da página de   DOCS.

Se você tiver comentários   relacionados à documentação, fique à vontade para registrá-los por meio deste   canal.

Agradecemos sua contribuição   aos nossos artigos.

Atenciosamente,
Equipe Internacional do   Microsoft DOCS
