### ISSUE TITLE
Erro na tradução para o Português

### ISSUE THREAD

**Issue by camilamcn** [MicrosoftDocs/powerbi-docs.pt-br#6]
Error: "Limite de tempo de cálculo – se um cálculo do visual do R exceder 60 MINUTOS, o script atingirá o tempo limite, resultando em erro."

Correct: "Limite de tempo de cálculo – se um cálculo do visual do R exceder 60 SEGUNDOS, o script atingirá o tempo limite, resultando em erro."

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 90c7931b-9fbb-bec4-09c4-9c827e4ec7a1
* Version Independent ID: 7ebc1400-482b-62e6-3747-bb7ffdb1dcf3
* Content: [Criar visualizações e análise avançadas usando scripts do R no Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/service-r-visuals#known-limitations)
* Content Source: [powerbi-docs/service-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/service-r-visuals.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
Olá, @camilamcn 
 
Agradecemos seus comentários. 
 
Vamos analisar seus comentários e daremos um retorno para você em breve. 
 
Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by LisandroSu** [comment]
Olá, @camilamcn ,  

Agradecemos seus comentários. 

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir [Criar visualizações e análise avançadas usando scripts do R no Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/service-r-visuals#known-limitations).  

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
