### ISSUE TITLE
Falta o login senha para acessar o GitHub

### ISSUE THREAD

**Issue by RenatoHadad** [MicrosoftDocs/powerbi-docs.pt-br#7]
Boa tarde no curso do PowerBI falta o login e senha para acessar o GitHub.
Observando o video pode-se encontrar Microsoft e ChakraCore como os valores necessários.

Não encontrei o ... para agendar as atualizações

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 94b08723-3d20-45e8-1a6e-348c33cb5ff2
* Version Independent ID: a201f1c5-9771-5eff-bac6-85de7058a8b3
* Content: [Introdução - Power BI](https://docs.microsoft.com/pt-br/power-bi/guided-learning/gettingstarted?tutorial-step=6)
* Content Source: [powerbi-docs/guided-learning/gettingstarted.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr.pt-BR/blob/live-sxs/powerbi-docs/guided-learning/gettingstarted.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #226](https://github.com/MicrosoftDocs/powerbi-docs/issues/226) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Olá, @RenatoHadad   

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/powerbi-docs/issues/226. 

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
