### ISSUE TITLE
Posso usar não sendo premium?

### ISSUE THREAD

**Issue by Fecerati** [MicrosoftDocs/powerbi-docs.pt-br#8]
Pessoal, tudo certo?
Apenas contas premium podem usar esse recurso?
Existe algum recurso similar pra quem não é premium?
Não consigo atualizar a minha base por que a busca pelos dados leva mais de 1h.
Abraço..

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Atualização incremental no Power BI Premium - Power BI](https://docs.microsoft.com/pt-br/power-bi/service-premium-incremental-refresh)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* GitHub Login: @christianwade
* Microsoft Alias: **chwade**

**Comment by christianwade** [comment]
Tudo bem!
Por enquanto, é apenas premium, mas planejamos permitir en pro também.
Em relação a busca mais de 1h, veja a parte no fim do artigo "Tempos limite de consulta". Talvez ajude mesmo sem Atualização incremental.

**Comment by LisandroSu** [comment]
Hi @christianwade! Thanks for answering the question.

Let us know when we can close this issue.

**Comment by christianwade** [comment]
Hi Lisandro, yes I think you can close it. Thanks!
