### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by IgorRozani** [MicrosoftDocs/powerbi-docs.pt-br#9]
The link "the index" in the README file is broken.

![image](https://user-images.githubusercontent.com/802968/47243450-6c60c000-d3c8-11e8-99e3-280095530c12.png)

**Comment by CeciAc** [comment]
Hi @Alisha-Acharya 
Please, check this issue

**Comment by CeciAc** [comment]
Hi @Alisha-Acharya @JasonCard 
any update on this?

**Comment by CeciAc** [comment]
Hi @Alisha-Acharya @JasonCard
any update on this?

**Comment by CeciAc** [comment]
Hi @Alisha-Acharya @JasonCard
any update on this?
@DavidPrio FYI

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #488](https://github.com/MicrosoftDocs/powerbi-docs/issues/488) via [**ZenHub**](https://www.zenhub.com/)

**Comment by JasonCard** [comment]
Hi @CeciAc @Alisha-Acharya @bodhigautam 
I've looked into this and found that README.md was outdated in loc repos due to localization tooling issue. Opened Loc Issue 54773 for following up on this issue.
